<?php

return [
    'indexTypes' => [

    ],
    'columnTypes' => [
            'bigIncrements' => 'bigIncrements',
            'bigInteger' => 'bigInteger',
            'binary' => 'binary',
            'boolean' => 'boolean',
            'char' => 'char',
            'dateTimeTz' => 'dateTimeTz',
            'dateTime' => 'dateTime',
            'date' => 'date',
            'decimal' => 'decimal',
            'double' => 'double',
//            'enum' => 'enum',
            'float' => 'float',
//            'foreignId' => 'foreignId',
//            'foreignIdFor' => 'foreignIdFor',
//            'foreignUlid' => 'foreignUlid',
//            'foreignUuid' => 'foreignUuid',
//            'geometryCollection' => 'geometryCollection',
//            'geometry' => 'geometry',
            'id' => 'id',
            'increments' => 'increments',
            'integer' => 'integer',
            'ipAddress' => 'ipAddress',
            'json' => 'json',
            'jsonb' => 'jsonb',
            'lineString' => 'lineString',
            'longText' => 'longText',
            'macAddress' => 'macAddress',
            'mediumIncrements' => 'mediumIncrements',
            'mediumInteger' => 'mediumInteger',
            'mediumText' => 'mediumText',
//            'morphs' => 'morphs',
            'multiLineString' => 'multiLineString',
            'multiPoint' => 'multiPoint',
            'multiPolygon' => 'multiPolygon',
            'nullableMorphs' => 'nullableMorphs',
            'nullableTimestamps' => 'nullableTimestamps',
            'nullableUlidMorphs' => 'nullableUlidMorphs',
            'nullableUuidMorphs' => 'nullableUuidMorphs',
            'point' => 'point',
            'polygon' => 'polygon',
            'rememberToken' => 'rememberToken',
            'set' => 'set',
            'smallIncrements' => 'smallIncrements',
            'smallInteger' => 'smallInteger',
            'softDeletesTz' => 'softDeletesTz',
            'softDeletes' => 'softDeletes',
            'string' => 'string',
            'text' => 'text',
            'timeTz' => 'timeTz',
            'time' => 'time',
            'timestampTz' => 'timestampTz',
            'timestamp' => 'timestamp',
            'timestampsTz' => 'timestampsTz',
            'timestamps' => 'timestamps',
            'tinyIncrements' => 'tinyIncrements',
            'tinyInteger' => 'tinyInteger',
            'tinyText' => 'tinyText',
            'unsignedBigInteger' => 'unsignedBigInteger',
            'unsignedDecimal' => 'unsignedDecimal',
            'unsignedInteger' => 'unsignedInteger',
            'unsignedMediumInteger' => 'unsignedMediumInteger',
            'unsignedSmallInteger' => 'unsignedSmallInteger',
            'unsignedTinyInteger' => 'unsignedTinyInteger',
            'ulidMorphs' => 'ulidMorphs',
            'uuidMorphs' => 'uuidMorphs',
            'ulid' => 'ulid',
            'uuid' => 'uuid',
            'year' => 'year',
]


];
